[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "grit"
version = "0.1.0"
description = "A Git implementation with my personal touch ✨"
authors = [{name="Mariem Ben Younes", email="maryemby21@gmail.com"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["python-dotenv", "typer"]

[project.scripts]
grit = "grit.__main__:main"
